SELECT M1.BASE_DT AS BASE_DT
         , M1.INCOME_RATIO AS BOND_INCOME_RATIO
         , M2.INCOME_RATIO AS KOSPI_INCOME_RATIO 
         , ROUND(M2.INCOME_RATIO*10 + M1.INCOME_RATIO * 0 , 3)/10 AS INCOME_10_0
         , ROUND(M2.INCOME_RATIO*9  + M1.INCOME_RATIO * 1 , 3)/10 AS INCOME_9_1
         , ROUND(M2.INCOME_RATIO*8  + M1.INCOME_RATIO * 2 , 3)/10 AS INCOME_8_2
         , ROUND(M2.INCOME_RATIO*7  + M1.INCOME_RATIO * 3 , 3)/10 AS INCOME_7_3
         , ROUND(M2.INCOME_RATIO*6  + M1.INCOME_RATIO * 4 , 3)/10 AS INCOME_6_4
         , ROUND(M2.INCOME_RATIO*5  + M1.INCOME_RATIO * 5 , 3)/10 AS INCOME_5_5
         , ROUND(M2.INCOME_RATIO*4  + M1.INCOME_RATIO * 6 , 3)/10 AS INCOME_4_6
         , ROUND(M2.INCOME_RATIO*3  + M1.INCOME_RATIO * 7 , 3)/10 AS INCOME_3_7
         , ROUND(M2.INCOME_RATIO*2  + M1.INCOME_RATIO * 8 , 3)/10 AS INCOME_2_8
         , ROUND(M2.INCOME_RATIO*1  + M1.INCOME_RATIO * 9 , 3)/10 AS INCOME_1_9
         , ROUND(M2.INCOME_RATIO*0  + M1.INCOME_RATIO * 10, 3)/10 AS INCOME_0_10
  FROM (

SELECT P1.BASE_DT AS BASE_DT
        , 1 +ROUND((P1.PRICE - P2.PRICE)/P2.PRICE, 3) AS INCOME_RATIO
  FROM (

SELECT Year(B.BASE_DT) AS YEAR
         , Month(B.BASE_DT) AS MONTH
         , MAX(BASE_DT) AS B_DT
  FROM TB_KOPSEF_BOND10 B
 GROUP BY Year(B.BASE_DT), Month(B.BASE_DT)

) T1
,(

SELECT Year(B.BASE_DT) AS YEAR
         , Month(B.BASE_DT) AS MONTH
         , MAX(BASE_DT) AS B_DT
  FROM TB_KOPSEF_BOND10 B
 GROUP BY Year(B.BASE_DT), Month(B.BASE_DT)

) T2
, TB_KOPSEF_BOND10 P1
, TB_KOPSEF_BOND10 P2
 WHERE dateserial(T1.YEAR, T1.MONTH, 1) = DateAdd ('m', 1, dateserial(T2.YEAR, T2.MONTH, 1) )
    AND P1.BASE_DT = T1.B_DT
    AND P2.BASE_DT = T2.B_DT

) M1
, (

SELECT P1.BASE_DT AS BASE_DT
        ,  1 + ROUND((P1.KOSPI_INDEX - P2.KOSPI_INDEX)/P2.KOSPI_INDEX, 3) AS INCOME_RATIO
  FROM (

SELECT Year(B.BASE_DT) AS YEAR
         , Month(B.BASE_DT) AS MONTH
         , MAX(BASE_DT) AS B_DT
  FROM TB_KOSPI_INDEX B
 GROUP BY Year(B.BASE_DT), Month(B.BASE_DT)

) T1
,(

SELECT Year(B.BASE_DT) AS YEAR
         , Month(B.BASE_DT) AS MONTH
         , MAX(BASE_DT) AS B_DT
  FROM TB_KOSPI_INDEX B
 GROUP BY Year(B.BASE_DT), Month(B.BASE_DT)

) T2
, TB_KOSPI_INDEX P1
, TB_KOSPI_INDEX P2
 WHERE dateserial(T1.YEAR, T1.MONTH, 1) = DateAdd ('m', 1, dateserial(T2.YEAR, T2.MONTH, 1) )
    AND P1.BASE_DT = T1.B_DT
    AND P2.BASE_DT = T2.B_DT

) M2
WHERE M1.BASE_DT = M2.BASE_DT
ORDER BY M1.BASE_DT ASC